import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { VideoProvider } from "./providers/VideoProvider";
import DynamicProviderWrapper from "./components/DynamicProviderWrapper";
import { UploadProvider } from "./providers/UploadProvider";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicProviderWrapper>
          <UploadProvider>
            <VideoProvider>
              <div className="min-h-screen flex flex-col">
                <main className="flex-grow overflow-y-auto pb-16">
                  {children}
                </main>
                <Navbar />
              </div>
            </VideoProvider>
          </UploadProvider>
        </DynamicProviderWrapper>
      </body>
    </html>
  );
}
